=== nyangate/jpos-example/src/dist/cfg/packager/mygeneric.dtd
<!ELEMENT Iso8583PostXml (MsgType, Fields)>
<!ELEMENT MsgType (#PCDATA)>
        <!ELEMENT Fields (
                Field_002?,
                Field_003?,
                Field_004?,
                Field_005?,
                Field_007?,
                Field_009?,
                Field_011?,
                Field_012?,
                Field_013?,
                Field_014?,
                Field_015?,
                Field_016?,
                Field_018?,
                Field_022?,
                Field_023?,
                Field_025?,
                Field_026?,
                Field_027?,
                Field_028?,
                Field_029?,
                Field_030?,
                Field_031?,
                Field_032?,
                Field_033?,
                Field_035?,
                Field_037?,
                Field_038?,
                Field_039?,
                Field_040?,
                Field_041?,
                Field_042?,
                Field_043?,
                Field_044?,
                Field_045?,
                Field_048?,
                Field_049?,
                Field_050?,
                Field_052?,
                Field_053?,
                Field_054?,
                Field_056?,
                Field_057?,
                Field_058?,
                Field_059?,
                Field_066?,
                Field_067?,
                Field_070?,
                Field_073?,
                Field_074?,
                Field_075?,
                Field_076?,
                Field_077?,
                Field_078?,
                Field_079?,
                Field_080?,
                Field_081?,
                Field_082?,
                Field_083?,
                Field_084?,
                Field_085?,
                Field_086?,
                Field_087?,
                Field_088?,
                Field_089?,
                Field_090?,
                Field_091?,
                Field_095?,
                Field_097?,
                Field_098?,
                Field_100?,
                Field_101?,
                Field_102?,
                Field_103?,
                Field_118?,
                Field_119?,
                Field_123?,
                Field_125?,
                Field_127_002?,
                Field_127_003?,
                Field_127_004?,
                Field_127_005?,
                Field_127_006?,
                Field_127_007?,
                Field_127_008?,
                Field_127_009?,
                Field_127_010?,
                Field_127_011?,
                Field_127_012?,
                Field_127_013?,
                Field_127_014?,
                Field_127_015?,
                Field_127_016?,
                Field_127_017?,
                Field_127_018?,
                Field_127_019?,
                Field_127_020?,
                Field_127_021?,
                Field_127_022?,
                Field_127_023?,
                Field_127_024?,
                Field_127_025?,
                Field_127_026?,
                Field_127_027?,
                Field_127_028?,
                Field_127_029?,
                Field_127_030?,
                Field_127_031?,
                Field_127_032?,
                Field_127_033?,
                Field_127_034?,
                Field_127_035?,
                Field_127_039?
                )>
        <!ELEMENT Field_002 (#PCDATA)>
        <!ELEMENT Field_003 (#PCDATA)>
        <!ELEMENT Field_004 (#PCDATA)>
        <!ELEMENT Field_005 (#PCDATA)>
        <!ELEMENT Field_007 (#PCDATA)>
        <!ELEMENT Field_009 (#PCDATA)>
        <!ELEMENT Field_011 (#PCDATA)>
        <!ELEMENT Field_012 (#PCDATA)>
        <!ELEMENT Field_013 (#PCDATA)>
        <!ELEMENT Field_014 (#PCDATA)>
        <!ELEMENT Field_015 (#PCDATA)>
        <!ELEMENT Field_016 (#PCDATA)>
        <!ELEMENT Field_018 (#PCDATA)>
        <!ELEMENT Field_022 (#PCDATA)>
        <!ELEMENT Field_023 (#PCDATA)>
        <!ELEMENT Field_025 (#PCDATA)>
        <!ELEMENT Field_026 (#PCDATA)>
        <!ELEMENT Field_027 (#PCDATA)>
        <!ELEMENT Field_028 (#PCDATA)>
        <!ELEMENT Field_029 (#PCDATA)>
        <!ELEMENT Field_030 (#PCDATA)>
        <!ELEMENT Field_031 (#PCDATA)>
        <!ELEMENT Field_032 (#PCDATA)>
        <!ELEMENT Field_033 (#PCDATA)>
        <!ELEMENT Field_035 (#PCDATA)>
        <!ELEMENT Field_037 (#PCDATA)>
        <!ELEMENT Field_038 (#PCDATA)>
        <!ELEMENT Field_039 (#PCDATA)>
        <!ELEMENT Field_040 (#PCDATA)>
        <!ELEMENT Field_041 (#PCDATA)>
        <!ELEMENT Field_042 (#PCDATA)>
        <!ELEMENT Field_043 (#PCDATA)>
        <!ELEMENT Field_044 (#PCDATA)>
        <!ELEMENT Field_045 (#PCDATA)>
        <!ELEMENT Field_048 (#PCDATA)>
        <!ELEMENT Field_049 (#PCDATA)>
        <!ELEMENT Field_050 (#PCDATA)>
        <!ELEMENT Field_052 (#PCDATA)>
        <!ELEMENT Field_053 (#PCDATA)>
        <!ELEMENT Field_054 (#PCDATA)>
        <!ELEMENT Field_056 (#PCDATA)>
        <!ELEMENT Field_057 (#PCDATA)>
        <!ELEMENT Field_058 (#PCDATA)>
        <!ELEMENT Field_059 (#PCDATA)>
        <!ELEMENT Field_066 (#PCDATA)>
        <!ELEMENT Field_067 (#PCDATA)>
        <!ELEMENT Field_070 (#PCDATA)>
        <!ELEMENT Field_073 (#PCDATA)>
        <!ELEMENT Field_074 (#PCDATA)>
        <!ELEMENT Field_075 (#PCDATA)>
        <!ELEMENT Field_076 (#PCDATA)>
        <!ELEMENT Field_077 (#PCDATA)>
        <!ELEMENT Field_078 (#PCDATA)>
        <!ELEMENT Field_079 (#PCDATA)>
        <!ELEMENT Field_080 (#PCDATA)>
        <!ELEMENT Field_081 (#PCDATA)>
        <!ELEMENT Field_082 (#PCDATA)>
        <!ELEMENT Field_083 (#PCDATA)>
        <!ELEMENT Field_084 (#PCDATA)>
        <!ELEMENT Field_085 (#PCDATA)>
        <!ELEMENT Field_086 (#PCDATA)>
        <!ELEMENT Field_087 (#PCDATA)>
        <!ELEMENT Field_088 (#PCDATA)>
        <!ELEMENT Field_089 (#PCDATA)>
        <!ELEMENT Field_090 (#PCDATA)>
        <!ELEMENT Field_091 (#PCDATA)>
        <!ELEMENT Field_095 (#PCDATA)>
        <!ELEMENT Field_097 (#PCDATA)>
        <!ELEMENT Field_098 (#PCDATA)>
        <!ELEMENT Field_100 (#PCDATA)>
        <!ELEMENT Field_101 (#PCDATA)>
        <!ELEMENT Field_102 (#PCDATA)>
        <!ELEMENT Field_103 (#PCDATA)>
        <!ELEMENT Field_118 (#PCDATA)>
        <!ELEMENT Field_119 (#PCDATA)>
        <!ELEMENT Field_123 (#PCDATA)>
        <!ELEMENT Field_125 (#PCDATA)>
        <!ELEMENT Field_127_002 (#PCDATA)>
        <!ELEMENT Field_127_003 (#PCDATA)>
        <!ELEMENT Field_127_004 (#PCDATA)>
        <!ELEMENT Field_127_005 (#PCDATA)>
        <!ELEMENT Field_127_006 (#PCDATA)>
        <!ELEMENT Field_127_007 (#PCDATA)>
        <!ELEMENT Field_127_008 (#PCDATA)>
        <!ELEMENT Field_127_009 (#PCDATA)>
        <!ELEMENT Field_127_010 (#PCDATA)>
        <!ELEMENT Field_127_011 (#PCDATA)>
        <!ELEMENT Field_127_012 (#PCDATA)>
        <!ELEMENT Field_127_013 (#PCDATA)>
        <!ELEMENT Field_127_014 (#PCDATA)>
        <!ELEMENT Field_127_015 (#PCDATA)>
        <!ELEMENT Field_127_016 (#PCDATA)>
        <!ELEMENT Field_127_017 (#PCDATA)>
        <!ELEMENT Field_127_018 (#PCDATA)>
        <!ELEMENT Field_127_019 (#PCDATA)>
        <!ELEMENT Field_127_020 (#PCDATA)>
        <!ELEMENT Field_127_021 (#PCDATA)>
        <!ELEMENT Field_127_022 (#PCDATA)>
        <!ELEMENT Field_127_023 (#PCDATA)>
        <!ELEMENT Field_127_024 (#PCDATA)>
        <!ELEMENT Field_127_025 (#PCDATA)>
        <!ELEMENT Field_127_026 (#PCDATA)>
        <!ELEMENT Field_127_027 (#PCDATA)>
        <!ELEMENT Field_127_028 (#PCDATA)>
        <!ELEMENT Field_127_029 (#PCDATA)>
        <!ELEMENT Field_127_030 (#PCDATA)>
        <!ELEMENT Field_127_031 (#PCDATA)>
        <!ELEMENT Field_127_032 (#PCDATA)>
        <!ELEMENT Field_127_033 (#PCDATA)>
        <!ELEMENT Field_127_034 (#PCDATA)>
        <!ELEMENT Field_127_035 (#PCDATA)>
        <!ELEMENT Field_127_039 (#PCDATA)>

=== nyangate/jpos-example/src/dist/cfg/packager/interswitch.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Iso8583PostXml SYSTEM "./mygeneric.dtd">
<Iso8583PostXml>
    <MsgType
    />
    <Fields>
        <Field_002
                id="2"
                length="19"
                name="PAN - PRIMARY ACCOUNT NUMBER"
                class="org.jpos.iso.IFA_LLNUM"/>
        <Field_003
                id="3"
                length="6"
                name="PROCESSING CODE"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_004
                id="4"
                length="12"
                name="AMOUNT, TRANSACTION"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_005
                id="5"
                length="12"
                name="AMOUNT, SETTLEMENT"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <!--<Field_006-->
        <!--id="6"-->
        <!--length="12"-->
        <!--name="AMOUNT, CARDHOLDER BILLING"-->
        <!--class="org.jpos.iso.IFA_NUMERIC"/>-->
        <Field_007
                id="7"
                length="10"
                name="TRANSMISSION DATE AND TIME"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <!--<Field_008-->
        <!--id="8"-->
        <!--length="8"-->
        <!--name="AMOUNT, CARDHOLDER BILLING FEE"-->
        <!--class="org.jpos.iso.IFA_NUMERIC"/>-->
        <Field_009
                id="9"
                length="8"
                name="CONVERSION RATE, SETTLEMENT"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <!--<Field_010-->
        <!--id="10"-->
        <!--length="8"-->
        <!--name="CONVERSION RATE, CARDHOLDER BILLING"-->
        <!--class="org.jpos.iso.IFA_NUMERIC"/>-->
        <Field_011
                id="11"
                length="6"
                name="SYSTEM TRACE AUDIT NUMBER"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_012
                id="12"
                length="6"
                name="TIME, LOCAL TRANSACTION"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_013
                id="13"
                length="4"
                name="DATE, LOCAL TRANSACTION"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_014
                id="14"
                length="4"
                name="DATE, EXPIRATION"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_015
                id="15"
                length="4"
                name="DATE, SETTLEMENT"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_016
                id="16"
                length="4"
                name="DATE, CONVERSION"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <!--<Field_017-->
        <!--id="17"-->
        <!--length="4"-->
        <!--name="DATE, CAPTURE"-->
        <!--class="org.jpos.iso.IFA_NUMERIC"/>-->
        <Field_018
                id="18"
                length="4"
                name="MERCHANTS TYPE"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <!--<isofield-->
        <!--id="19"-->
        <!--length="3"-->
        <!--name="ACQUIRING INSTITUTION COUNTRY CODE"-->
        <!--class="org.jpos.iso.IFA_NUMERIC"/>-->
        <!--<isofield-->
        <!--id="20"-->
        <!--length="3"-->
        <!--name="PAN EXTENDED COUNTRY CODE"-->
        <!--class="org.jpos.iso.IFA_NUMERIC"/>-->
        <!--<isofield-->
        <!--id="21"-->
        <!--length="3"-->
        <!--name="FORWARDING INSTITUTION COUNTRY CODE"-->
        <!--class="org.jpos.iso.IFA_NUMERIC"/>-->
        <Field_022
                id="22"
                length="3"
                name="POINT OF SERVICE ENTRY MODE"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_023
                id="23"
                length="3"
                name="CARD SEQUENCE NUMBER"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_024
                id="24"
                length="3"
                name="NETWORK INTERNATIONAL IDENTIFIEER"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_025
                id="25"
                length="2"
                name="POINT OF SERVICE CONDITION CODE"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_026
                id="26"
                length="2"
                name="POINT OF SERVICE PIN CAPTURE CODE"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_027
                id="27"
                length="1"
                name="AUTHORIZATION IDENTIFICATION RESP LEN"
                class="org.jpos.iso.IFA_NUMERIC"/>
        <Field_028
                id="28"
                length="9"
                name="AMOUNT, TRANSACTION FEE"
                class="org.jpos.iso.IFA_AMOUNT"/>
        <Field_029
                id="29"
                length="9"
                name="AMOUNT, SETTLEMENT FEE"
                class="org.jpos.iso.IFA_AMOUNT"/>
        <Field_030
                id="30"
                length="9"
                name="AMOUNT, TRANSACTION PROCESSING FEE"
                class="org.jpos.iso.IFA_AMOUNT"/>
        <Field_031
                id="31"
                length="9"
                name="AMOUNT, SETTLEMENT PROCESSING FEE"
                class="org.jpos.iso.IFA_AMOUNT"/>
        <Field_032
                id="32"
                length="11"
                name="ACQUIRING INSTITUTION IDENT CODE"
                class="org.jpos.iso.IFA_LLNUM"/>
        <Field_033
                id="33"
                length="11"
                name="FORWARDING INSTITUTION IDENT CODE"
                class="org.jpos.iso.IFA_LLNUM"/>
        <!--<isofield-->
        <!--id="34"-->
        <!--length="28"-->
        <!--name="PAN EXTENDED"-->
        <!--class="org.jpos.iso.IFA_LLCHAR"/>-->
        <Field_035
                id="35"
                length="37"
                name="TRACK 2 DATA"
                class="org.jpos.iso.IFA_LLNUM"/>
        <!--<isofield-->
        <!--id="36"-->
        <!--length="104"-->
        <!--name="TRACK 3 DATA"-->
        <!--class="org.jpos.iso.IFA_LLLCHAR"/>-->
        <Field_037
                id="37"
                length="12"
                name="RETRIEVAL REFERENCE NUMBER"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_038
                id="38"
                length="6"
                name="AUTHORIZATION IDENTIFICATION RESPONSE"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_039
                id="39"
                length="2"
                name="RESPONSE CODE"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_040
                id="40"
                length="3"
                name="SERVICE RESTRICTION CODE"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_041
                id="41"
                length="8"
                name="CARD ACCEPTOR TERMINAL IDENTIFICACION"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_042
                id="42"
                length="15"
                name="CARD ACCEPTOR IDENTIFICATION CODE"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_043
                id="43"
                length="40"
                name="CARD ACCEPTOR NAME/LOCATION"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_044
                id="44"
                length="25"
                name="ADITIONAL RESPONSE DATA"
                class="org.jpos.iso.IFA_LLCHAR"/>
        <Field_045
                id="45"
                length="76"
                name="TRACK 1 DATA"
                class="org.jpos.iso.IFA_LLCHAR"/>
        <!--<Field_046-->
        <!--id="46"-->
        <!--length="999"-->
        <!--name="ADITIONAL DATA - ISO"-->
        <!--class="org.jpos.iso.IFA_LLLCHAR"/>-->
        <!--<isofield-->
        <!--id="47"-->
        <!--length="999"-->
        <!--name="ADITIONAL DATA - NATIONAL"-->
        <!--class="org.jpos.iso.IFA_LLLCHAR"/>-->
        <Field_048
                id="48"
                length="999"
                name="ADITIONAL DATA - PRIVATE"
                class="org.jpos.iso.IFA_LLLCHAR"/>
        <Field_049
                id="49"
                length="3"
                name="CURRENCY CODE, TRANSACTION"
                class="org.jpos.iso.IF_CHAR"/>
        <Field_050
                id="50"
                length="3"
                name="CURRENCY CODE, SETTLEMENT"
                class="org.jpos.iso.IF_CHAR"/>
        <!--<isofield-->
        <!--id="51"-->
        <!--length="3"-->
        <!--name="CURRENCY CODE, CARDHOLDER BILLING"-->
        <!--class="org.jpos.iso.IF_CHAR"/>-->
        <Field_052
                id="52"
                length="8"
                name="PIN DATA"
                class="org.jpos.iso.IFB_BINARY"/>
        <Field_053
                id="53"
                length="48"
                name="SECURITY RELATED CONTROL INFORMATION"
                class="org.jpos.iso.IFB_BINARY "/>
        <Field_054
                id="54"
                length="120"
                name="ADDITIONAL AMOUNTS"
                class="org.jpos.iso.IFA_LLLCHAR"/>
        <!--<isofield-->
        <!--id="55"-->
        <!--length="999"-->
        <!--name="RESERVED ISO"-->
        <!--class="org.jpos.iso.IFA_LLLCHAR"/>-->
        <Field_056
                id="56"
                length="4"
                name="MESSAGE REASON CODE"
                class="org.jpos.iso.IFA_LLLCHAR"/>
        <Field_057
                id="57"
                length="3"
                name="AUTHORIZATION LIFE-CYCLE CODE"
                class="org.jpos.iso.IFA_LLLCHAR"/>
        <Field_058
                id="58"
                length="11"
                name="AUTHORIZING AGENT ID CODE"
                class="org.jpos.iso.IFA_LLLCHAR"/>
        <Field_059
                id="59"
                length="255"
                name="ECHO DATA"
                class="org.jpos.iso.IFA_LLLCHAR"/>
        <!--<isofield-->
